config/routes.rb
Bigheart::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :users do
    member do
      get :stories, action: "users_stories"
    end
  end

  resources :stories do
    collection do
      get :manage, action: "manage_stories"
    end
    member do
      get 'update_state', to: 'stories#update_state'
    end
  end

  post 'send_mail/report'

  root :to => "stories#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :stories

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  # save facebook account info
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.new(name:auth.extra.raw_info.name, provider:auth.provider, uid:auth.uid, email:auth.info.email, password:Devise.friendly_token[0,20])
      user.skip_confirmation!
      user.add_role :user
      user.save
    end
    user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :authenticate_user!

  def index
    authorize! :index, @user
    @users = User.all
  end

  def show
    authorize! :show, @user
    @user = User.find(params[:id])
  end

  def update
    authorize! :update, @user
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user
    user = User.find(params[:id])
    unless user.id == current_user.id
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  def users_stories
    @stories = Story.where(user_id: current_user.id)
  end

private
  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation, :uid, :provider)
    # , :provider, :uid)
  end
end

app/views/users/_user.html.haml
.modal.fade{:id => "role-options-#{user.id}", :style => "display: none;"}
  .modal-dialog
    .modal-content
      = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
        .modal-header
          %a.close{"data-dismiss" => "modal"} ×
          %h3.modal-title Change Role
        .modal-body
          = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
        .modal-footer
          = f.submit "Change Role", :class => "btn btn-primary"
          %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-primary{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}

app/views/users/users_stories.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th story name
        %th.col-md-2{:colspan => '2'} 編輯或刪除文章
        %th.col-md-1 current state
    %tbody
      - @stories.each do |story|
        %tr
          %td= link_to story.story_name, story_path(story.id)
          %td= link_to (button_tag '編輯文章', class: "btn btn-primary"), "#{edit_story_path(story.id)}"
          %td= link_to (button_tag '刪除文章', class: "btn btn-danger"), "#{story_path(story.id)}", confirm: '確定刪除?', method: :delete
          %td= Story::TRANS_STATES[story.state]