config/routes.rb
Bigheart::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :users do
    member do
      get :stories, action: "users_stories"
    end
  end

  resources :stories do
    collection do
      get :manage, action: "manage_stories"
    end
    member do
      get 'update_state', to: 'stories#update_state'
    end
  end

  post 'send_mail/report'

  root :to => "stories#index"
end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessor :report_text

  validates :appear_location, :contact_email, :info_from, :story_details, presence:true
  validates :story_name, presence:true, uniqueness: true

  belongs_to :user
  mount_uploader :image, ImageUploader

  serialize :appear_day

  CITIES = Hashie::Mash.new(
      "基隆市" => ".基隆市",
      "臺北市" => ".臺北市",
      "新北市" => ".新北市",
      "桃園縣" => ".桃園縣",
      "新竹縣" => ".新竹縣",
      "新竹市" => ".新竹市",
      "苗栗縣" => ".苗栗縣",
      "臺中市" => ".臺中市",
      "彰化縣" => ".彰化縣",
      "南投縣" => ".南投縣",
      "雲林縣" => ".雲林縣",
      "嘉義縣" => ".嘉義縣",
      "嘉義市" => ".嘉義市",
      "臺南市" => ".臺南市",
      "高雄市" => ".高雄市",
      "屏東縣" => ".屏東縣",
      "臺東縣" => ".臺東縣",
      "花蓮縣" => ".花蓮縣",
      "屏東縣" => ".屏東縣",
      "宜蘭縣" => ".宜蘭縣",
      "澎湖縣" => ".澎湖縣",
      "金門縣" => ".金門縣"
  )

  CITIES_MARKER = Hashie::Mash.new(
      "基隆" => "基隆車站",
      "臺北&新北" => "臺北車站",
      "桃園" => "桃園車站",
      "新竹" => "新竹車站",
      "苗栗" => "苗栗車站",
      "臺中" => "臺中車站",
      "彰化" => "彰化車站",
      "南投" => "濁水車站",
      "雲林" => "雲林車站",
      "嘉義" => "嘉義車站",
      "臺南" => "臺南車站",
      "高雄" => "高雄車站",
      "屏東" => "屏東車站",
      "臺東" => "臺東車站",
      "花蓮" => "花蓮車站",
      "宜蘭" => "宜蘭車站",
      "澎湖" => "馬公市",
      "金門" => "山外車站"
  )

  #define state machine
  STATES = Hashie::Mash.new(
      :pending => 0,
      #edited: 1,
      :rejected => 1,
      :published => 2
  )

  TRANS_STATES = Hashie::Mash.new(
      "#{STATES.pending}" => '審核中',
      #"#{STATES.edited}" => '編輯中',
      "#{STATES.rejected}" => '駁回',
      "#{STATES.published}" => '已刊登',
  )

  state_machine :state, initial: :pending do
    STATES.each do |state_name, state_value|
      state state_name.to_sym, value: state_value
    end

    #event :edited do
    #  transition [:edited, :pending, :rejected, :published] => :edited
    #end

    event :pending do
      transition [:published, :rejected] => :pending
    end

    event :rejected do
      transition [:pending, :published] => :rejected
    end

    event :published do
      transition [:pending, :published, :rejected] => :published
    end
  end

  # get story location coordinate
  def self.get_coordinate(city,location)
    Geokit::Geocoders::GoogleGeocoder.geocode("#{city}#{location}").ll
  end

  # manage location coordinate for saving
  def self.manage_coordinate(city, locations)
    coordinates = {}
    locations.split(',').each do |l|
      coordinates["#{l}"] = {}
      coordinates["#{l}"] = get_coordinate(city, l)
    end
    return coordinates
  end

  def self.parse_location_json(locations)
    JSON.parse(locations)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  #before_action :show, :check_state
  before_filter :set_cache_buster, only: :index

  def index
    # TODO: change the hardcoded value to reference
    @stories = Story.where(state: Story::STATES.published)
    # get location latitude and longitude
    @details = {}
    @stories.each do |s|
      Story.parse_location_json(s.appear_location).each do |l, c|
        if @details[c].present?
          @details[c] << {"title" => s.story_name, "story_id" => s.id}
        else
          @details[c] = []
          @details[c] << {"title" => s.story_name, "story_id" => s.id}
        end
      end
    end
  end

  def show
    story = Story.find(params[:id])

    # get location latitude and longitude
    @latitude = []
    @longitude = []

    Story.parse_location_json(story.appear_location).each do |l, c|
      lat_n_lng = c.split(',')
      @latitude << lat_n_lng[0]
      @longitude << lat_n_lng[1]
    end

    # set og tags for facebook like and share
    set_meta_tags og: {title: "#{story.story_name}", description: "#{story.story_details}", type: "article", url: "http://bigheart.tw/stories/#{story.id}", image: "#{story.image}"}
    set_meta_tags fb: {app_id: "250816725069932"}
    if story.state != Story::STATES.published
      # check admin role if story state isn't published
      if user_signed_in? && current_user.has_role?(:admin)
        @story = story
      else
        flash[:alert] = "這篇文章尚未通過審核!!"
        redirect_to root_path
      end
    else
      @story = story
    end
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)

    if @story.valid?
      #get story location coordinate
      @story.appear_location = Story.manage_coordinate(story_params[:city], story_params[:appear_location]).to_json
      #story.user_id = current_user.id
      @story.save
      redirect_to stories_path, notice: "故事將於審查後發佈."
    else
      flash.now.alert = "請檢查您所輸入的資訊是否有誤!!"
      render action: 'new'
    end
  end

  def edit
    authorize! :update, @story
    @story = Story.find(params[:id])
    location = []
    Story.parse_location_json(@story.appear_location).keys.each do |l|
      location << l
    end
    @location = location.join(',')
  end

  def update
    @story = Story.find(params[:id])

    if @story.update_attributes(story_params)
      @story[:appear_location] = Story.manage_coordinate(story_params[:city], story_params[:appear_location]).to_json
      @story.published!
      redirect_to manage_stories_path, notice: '成功編輯故事.'
    else
      render action: 'edit'
    end
  end

  def manage_stories
    authorize! :manage_stories, @stories
    @stories = Story.all
  end

  def update_state
    authorize! :manage_stories, Story
    story = Story.find(params[:id])
    story.send(params[:story][:state])
    #if params[:story][:state].to_sym == :published
    #  story.published!
    #elsif params[:story][:state] == 'rejected'
    #  story.rejected!
    #elsif params[:story][:state] == 'pending'
    #  story.pending!
    #end
    redirect_to manage_stories_path, notice: "已變更狀態為#{Story::TRANS_STATES[story.state]}"
  end

  def destroy
    authorize! :manage_stories, Story
    story = Story.find(params[:id])
    story.destroy

    redirect_to manage_stories_path
  end

private
  def story_params
    params.require(:story).permit(:story_name, :appear_time_from, :appear_time_to, :city, :appear_location, :info_from, :story_details, :image, :contact_email, :appear_day => [])
  end

  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
  end
end

app/helpers/story_helper.rb
module StoryHelper

end

app/views/stories/_feedback.html.haml
.modal.fade{:id => "feedback", :style => "display: none;"}
  .modal-dialog
    .modal-content
      = simple_form_for :story, :html => {:class => 'form-horizontal' }, :url => url_for(:action => 'feedback', :controller => 'stories') do |f|
        .modal-header
          %a.close{"data-dismiss" => "modal"} ×
          %h3.modal-title 回報故事
        .modal-body
          .radio
            %label
              = f.input :report_reason, label: false, :input_html => {type: "radio", value: "故事非屬實"}
              故事非屬實
          .radio
            %label
              = f.input :report_reason, label: false, :input_html => {type: "radio", value: "內容有誤"}
              內容有誤
          .radio
            %label
              = f.input :report_reason, label: false, :input_html => {type: "radio", value: "內容與本網站無關"}
              內容與本網站無關
          .form-group
            = f.input :report_text, label: "其他或建議", :input_html => {class: "form-control", :rows => "8", :col => "30"}, as: :text, class: "form-control input-lg", type: "text"
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} 關閉
          = f.submit "送出回報資訊", class: "btn btn-primary"

app/views/stories/_report.html.haml
.modal.fade{:id => "report", :style => "display: none;"}
  .modal-dialog
    .modal-content
      = simple_form_for :report, :html => {:class => 'form-horizontal' }, :url => url_for(:action => 'report', :controller => 'send_mail') do |f|
        -story_name = Story.find(params[:id]).story_name
        .modal-header
          %a.close{"data-dismiss" => "modal"}
            %i.fa.fa-times-circle
          %h3.modal-title 回報#{story_name}的資訊
        .modal-body
          = f.input :story_name, as: :hidden, :input_html => {value: story_name}
          .radio
            %label
              = f.input :type, label: false, :input_html => {type: "radio", value: "故事非屬實"}
              故事非屬實
          .radio
            %label
              = f.input :type, label: false, :input_html => {type: "radio", value: "內容有誤"}
              內容有誤
          .radio
            %label
              = f.input :type, label: false, :input_html => {type: "radio", value: "內容與本網站無關"}
              內容與本網站無關
          .form-group
            = f.input :report_msg, label: "其他", required: false, :input_html => {class: "form-control", :rows => "8", :col => "30"}, as: :text, class: "form-control input-lg", type: "text"
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} 關閉
          %button.send_mail.btn.btn-primary{:action => 'report', :controller => 'send_mail'} 送出回報資訊

app/views/stories/_slogan.html.haml
#slogan.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %a.close{"data-dismiss" => "modal"} ×
        %h1
          %strong.modal-title What is Bigheart
      .modal-body
        %h3
          %strong 在台灣有許多真正急需幫助的人，他們透過販賣生活用品或食物來換取所需的生活或醫療費用。
        %p
          %h4 由於透過社群網站(如facebook)分享這類訊息時，通常夾雜著大量其他的資訊，並大大的降低了這些資訊的曝光率。再者，因為社群網站資訊流動量過大，往往會造成這些人只能獲得短暫性的幫助，無法持續不間斷的獲得他們需要的資源。為了有效的將這些訊息傳達給更多人，並且讓人們能夠用更便捷的方式來得到這些人的資訊，Bigheart因此而誕生。透過Bigheart，不論您身在何方，都能以最便捷的方式得知您所在的縣市有哪些人正等著您的幫助。另外，您除了可以從這裡獲得這些資訊，也可以將自己所知道的資訊分享出去。別再猶豫了!!快來看看有哪些人需要幫助，或告訴大家哪裡還有人等著我們伸出援手，將這份溫暖的訊息傳達到所有人心裡吧!!
      .modal-footer
        .btn.btn-primary{"data-dismiss" => "modal"} 關閉

app/views/stories/_state.html.haml
- Story.all.each do |story|
  .modal.fade{:id => "state-options-#{story.id}", :style => "display: none;"}
    .modal-dialog
      .modal-content
        = simple_form_for story, :url => update_state_story_path(story.id), :html => {method: 'get', :class => 'form-horizontal' } do |f|
          .modal-header
            %a.close{"data-dismiss" => "modal"} ✖︎
            %h3.modal-title 變更狀態
          .modal-body
            - state = story.state_events
            = f.input :state, :collection => state, :as => :radio_buttons, :label => false, :item_wrapper_class => 'inline'
          .modal-footer
            = f.submit "Change state", :class => "btn btn-primary"
            %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close

app/views/stories/_stories.html.haml
-#-*- encoding : utf-8 -*-
%h4
  %strong
    %i.fa.fa-exclamation-circle.fa-lg
    提供故事後仍需經過管理員審查才會發佈到故事列表中，* 為必填資訊
%p
  = simple_form_for @story, :html => {:class => 'form-vertical', role: "form"} do |f|
    .form-group
      = f.input :story_name, label: "故事標題", :input_html => {class: "form-control"}, placeholder: "#{@story.story_name}", :required => true
    .form-group
      = f.input :contact_email, label: "聯絡信箱", :input_html => {class: "form-control"}, hint: "若提供的故事遭其他使用者回報資訊錯誤管理員會以此信箱聯絡您詢問較正確的資訊以利修正",placeholder: "您的電子郵件", :required => true
    .form-group.appear_day
      = f.input :appear_day, label: "時段", as: :check_boxes, collection: ["星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期天", "週一至週日", "不確定"]
    .form-group
      .form-inline
        .form-group
          於
        .form-group
          = f.input :appear_time_from, label: false, :input_html => {class: "form-control"}, class: "time", collection: ["1:00","2:00","3:00","4:00","5:00","6:00","7:00","8:00","9:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24:00"], selected: "#{@story.appear_time_from}", include_blank: "不確定"
        .form-group
          至
        .form-group
          = f.input :appear_time_to, label: false, :input_html => {class: "form-control"}, class: "time", collection: ["1:00","2:00","3:00","4:00","5:00","6:00","7:00","8:00","9:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24:00"], selected: "#{@story.appear_time_to}", include_blank: "不確定"
      = "範例: 於 11:00 至 17:00"
    .form-group
      = f.input :city, label: "縣市", :input_html => {class: "form-control"}, class: "city", collection: Story::CITIES.keys, selected: "#{@story.city}"
    .form-group
      = f.input :appear_location, label: "地點", style: {width: "250px"}, :input_html => {id: "location_input", class: "form-control", value: "#{@location}", "data-role" => "tagsinput"}, hint: "每輸入完一個地點記得按一下\"Enter\"喔!!", type: "text", :required => true
    .form-group
      = f.input :info_from, label: "資訊來源", :input_html => {class: "form-control"}, :required => true
    .form-group
      = f.input :story_details, label: "故事內容", :input_html => {class: "form-control", :rows => "15", style: "width: 526px"}, as: :text, class: "form-control input-lg", type: "text", placeholder: "#{@story.story_details}", :required => true
    .form-group
      = f.input :image, as: :file, label: "上傳照片"
    - if @story.image.file.nil?
    -else
      .form-group
        = image_tag @story.image_url(:thumb).to_s
    - if action_name == 'edit'
      .form-group
        = f.button :submit, "完成編輯", class: "btn btn-primary"
    - else
      .form-group
        = f.button :submit, "提供資訊", class: "btn btn-primary", role: "button"
:javascript
  $('#location_input').tagsInput();

app/views/stories/edit.html.haml
= render 'stories/stories'

app/views/stories/index.html.haml
-#.row
- if cookies[:site] == nil
  - cookies.permanent[:site] = {value: "bigheart"}
  = render 'stories/slogan'
- else
  - Rails.cache.clear
%form.form-inline.pull-right
  %button.btn.btn-info{"data-toggle" => "modal", :href => "#toggle_map"} 觀看地圖
  = render 'layouts/index_map'
  .form-group
    #filters_city
      %select#cities.form-control{style: "padding-right: 1px;"}
        %option{value: "*"} 查看全部
        - Story::CITIES.each do |city, city_class|
          %option{value: "#{city_class}"} #{city}
#stories{style: "margin-top: 50px"}
  - @stories.each do |s|
    .story{class: s.city}
      - if s.image.file.nil?
      -else
        = image_tag s.image_url(:thumb).to_s
      %h3
        %strong.story_title [#{s.city}] #{s.story_name}
      %strong.location
        = '地點: '
        - JSON.parse(s.appear_location).keys.each do |t|
          = "#{t}"
      %p
        %strong.appear_time
          時段:
          - s.appear_day.select{|d| d.present?}.each do |d|
            = "#{d}"
          %p
            - if s.appear_time_from.present? || s.appear_time_to.present?
              = "#{s.appear_time_from} - #{s.appear_time_to}"
      %p.index.story_details #{simple_format(truncate(s.story_details), length: 50, style:"font-size: 1.3em")}
      %a.btn.btn-primary{href: "/stories/#{s.id}", role: "button"} 繼續閱讀 »

app/views/stories/manage_stories.html.haml
- if can? :manage, :all
  %h3 Users
  .span8
    %table.table.table-condensed
      %thead
        %tr
          %th 故事名稱
          %th 發佈人聯絡信箱
          %th.col-md-1 目前狀態
          %th.col-md-3 編輯
      %tbody
        - @stories.each do |story|
          -#- user = User.where(id: story.user_id)[0]
          -#- binding.pry
          %tr
            %td= link_to story.story_name, story_path(story.id)
            -#%td= user.name
            %td= story.contact_email
            %td= Story::TRANS_STATES[story.state]
            %td
              %a.btn.btn-primary{"data-toggle" => "modal", :href => "#state-options-#{story.id}", :type => "button"} 變更狀態
              %a.btn.btn-primary{:href => edit_story_path(story.id), :type => "button"} 編輯文章
              = link_to("刪除文章", story_path(story.id), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-danger')
              = render 'state'
            -#%td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/stories/new.html.haml
= render 'stories/stories'

app/views/stories/show.html.haml
.row
  .col-md-6
    .fb-like{"data-action" => "like", "data-href" => "http://bigheart.tw/stories/#{@story.id}", "data-layout" => "button", "data-share" => "true", "data-show-faces" => "false"}
  .col-md-6
    %p.pull-right
      %a.fa.fa-exclamation-triangle.btn.btn-warning.btn-lg{"data-toggle" => "modal", :href => "#report"} 回報故事資訊錯誤
      = render 'stories/report'
%h1
  %strong.story_title
    = @story.story_name + '的故事'
%p
  %strong.location
    = '地點: '
    = "#{@story.city}"
    - JSON.parse(@story.appear_location).keys.each do |l|
      = "#{l}"
.row
  .col-sm-6
    %p
      %strong.appear_time
        = '時段: '
        - @story.appear_day.select{|d| d.present?}.each do |day|
          = "#{day}"
        - if @story.appear_time_from.present? || @story.appear_time_to.present?
          = ", #{@story.appear_time_from} - #{@story.appear_time_to}"
    %p.info_from
      = '資訊來源: ' "#{@story.info_from}"
    %p
      .story_details
        = simple_format(@story.story_details)
  .col-sm-6
    %p
      - if @story.image.file.nil?
      - else
        %img.img-responsive{src: "#{@story.image_url(:show).to_s}"}
-#- JSON.parse(@story.appear_location).each do |l, c|
.panel.panel-info{style: "margin-top: 15px;"}
  .panel-heading 地圖
  .panel-body
    #show_map{style: "height: 300px; width: auto; position: relative;", "data-latitude" => "#{@latitude}", "data-longitude" => "#{@longitude}"}
:javascript
  var coordinate = $('#show_map'),
      latitude = coordinate.data('latitude'),
      longitude = coordinate.data('longitude'),
      action = coordinate.data('action');
  var map = new GMaps({
          el: '#show_map',
          lat: latitude[0],
          lng: longitude[0],
          zoom: 16
      });
  for (i = 0; i < latitude.length; i++){
          map.addMarker({
              lat: latitude[i],
              lng: longitude[i],
              icon: '/assets/red-dot.png'
          });
      }
  map.setCenter(latitude[0], longitude[0]);

  if (latitude.length > 1) {
      map.fitZoom(latitude[0], longitude[0]);
  };