config/routes.rb
Bigheart::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :users do
    member do
      get :stories, action: "users_stories"
    end
  end

  resources :stories do
    collection do
      get :manage, action: "manage_stories"
    end
    member do
      get 'update_state', to: 'stories#update_state'
    end
  end

  post 'send_mail/report'

  root :to => "stories#index"
end

app/views/layouts/_feedback.html.haml
.modal.fade{:id => "feedback", :style => "display: none;"}
  .modal-dialog
    .modal-content
      = simple_form_for :report, :html => {:class => 'form-horizontal' }, url: send_mail_report_path do |f|
        .modal-header
          %a.close{"data-dismiss" => "modal"}
            %i.fa.fa-times-circle
          %h3.modal-title 聯絡管理員
        .modal-body
          .radio
            %label
              = f.input :type, label: false, :input_html => {type: "radio", value: "提供建議"}
              提供建議
          .radio
            %label
              = f.input :type, label: false, :input_html => {type: "radio", value: "錯誤回報"}
              錯誤回報
          .form-group
            = f.input :report_msg, label: "建議或錯誤資訊", :input_html => {class: "form-control", :rows => "8", :col => "30"}, as: :text, class: "form-control input-lg", type: "text", :required => true
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} 關閉
          %button.send_mail.btn.btn-primary{:action => 'report', :controller => 'send_mail'} 提交訊息

app/views/layouts/_index_map.html.haml
.modal.fade{:id => "toggle_map", :style => "display: none;"}
  .modal-dialog
    .modal-content
      .modal-header
        %a.close{"data-dismiss" => "modal"}
          %i.fa.fa-times-circle
        %h3.modal-title 地圖
        #fail
      .modal-body
        #users_city
          .form-group.col-md-3{style: "margin-bottom: 20px; padding-left: 0px; padding-right: 30px;"}
            %select#selected_city.form-control
              - Story::CITIES_MARKER.each do |city, city_class|
                %option{value: "#{city_class}"} #{city}
        .clearfix
        #index_map{"data-action" => "index", "data-details" => "#{@details.to_json}", "data-coordinates" => "#{@details.keys}"}
      .modal-footer{style: "margin-top: 0px"}
        %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} 關閉
:javascript
    var index_map = $('#index_map'),
        coordinates = index_map.data('coordinates'),
        action = index_map.data('action');
    GMaps.geolocate({
        success: function(position){
            //filter stories which is in the same city with users location
                //GMaps.geocode({
                //    lat: position.coords.latitude,
                //    lng: position.coords.longitude,
                //    callback: function(results, status) {
                //        if (status == 'OK') {
                //            $('#stories').isotope({
                //                filter: '.' + results[4]['address_components'][0]['long_name'].replace(/ /g,'')
                //            });
                //            $('#filters_city select').select2('val', results[4]['address_components'][0]['long_name'].replace(/ /g,''));
                //            //console.log(city)
                //            //var after = $('#filters_city select').val();
                //        }
                //        //console.log(after)
                //    }
                //});
            var users_lat = position.coords.latitude,
                users_lng = position.coords.longitude;
            var map = new GMaps({
                el: '#index_map',
                lat: users_lat,
                lng: users_lng,
                height: '558px',
                width: 'auto',
                zoom: 14
            });

            $('#toggle_map').on('shown.bs.modal', function () {
                map.refresh();
                if (typeof chosen_lat != 'undefined' && typeof chosen_lng != 'undefined') {
                    map.setCenter(chosen_lat, chosen_lng);
                }
                else {
                    map.setCenter(users_lat, users_lng)
                }
            });

            var init_marker = map.addMarker({
                lat: users_lat,
                lng: users_lng,
                title: '您的位置',
                icon: '/assets/green-dot.png',
                infoWindow: {
                    content: '<p>您的位置</p>'
                }
            });

            for (c = 0; c < coordinates.length; c++){
                lat_lng = coordinates[c].split(','),
                latitude = lat_lng[0],
                longitude = lat_lng[1],
                details = index_map.data('details')[coordinates[c]];
                content = [];
                for (t = 0; t < details.length; t++){
                    title = details[t]['title'],
                    story_id = details[t]['story_id'],
                    content_html = '<a href="stories/' + story_id + '">' + title + '</a>',
                    content.push(content_html);
                    if (users_lat == latitude && users_lng == longitude) {
                        map.addMarker({
                            lat: parseFloat(latitude) + 0.0001,
                            lng: parseFloat(longitude) + 0.0001,
                            icon: '/assets/red-dot.png',
                            infoWindow: {
                                content: content.join("<br/>")
                            }
                        });
                    }
                    else {
                        map.addMarker({
                            lat: latitude,
                            lng: longitude,
                            icon: '/assets/red-dot.png',
                            title: title,
                            infoWindow: {
                                content: content.join("<br/>")
                            }
                        });
                    }
                }
            }

            $('#users_city select').change(function(){
            $('#fail').hide();
                GMaps.geocode({
                    address: $('#users_city select').val(),
                    callback: function(results, status) {
                        if (status == 'OK') {
                             init_marker.setMap(null);
                             if (typeof chosen_marker != 'undefined') {
                                chosen_marker.setMap(null);
                             }
                             chosen_lat = results[0]['geometry']['location']['d']
                             chosen_lng = results[0]['geometry']['location']['e']
                             chosen_marker = map.addMarker({
                                lat: parseFloat(chosen_lat) + 0.0001,
                                lng: parseFloat(chosen_lng) + 0.0001,
                                title: '您所選擇的定位點',
                                icon: '/assets/green-dot.png',
                             });
                             map.setCenter(chosen_lat, chosen_lng);
                        }
                    }
                });
            })
            //add marker when user location and story locations distance are smaller than 5km
                //for (t = 0; t < titles.length; t++){
                //    var title = details[titles[t]]
                //        latitude = title['latitude'],
                //        longitude = title['longitude'];
                //    for (i = 0; i < latitude.length; i++){
                //        var user_point = new google.maps.LatLng(position.coords.latitude, position.coords.longitude),
                //            story_point = new google.maps.LatLng(latitude[i], longitude[i]),
                //            distance = google.maps.geometry.spherical.computeDistanceBetween(user_point, story_point);
                //        if(distance < 5000){
                //            map.addMarker({
                //                lat: latitude[i],
                //                lng: longitude[i],
                //                icon: '/assets/red-dot.png',
                //                infoWindow: {
                //                    content: '<p>' + titles[t] + '</p>'
                //                }
                //            });
                //        }
                //    }
                //}
        },
        error: function(error){
            console.log('Geolocation failed: '+error.message)
            $('#users_city').show()
            $('#fail').html('由於無法取得您的所在位置，請您允許網站存取您的位置或選擇您想瀏覽的城市。')
            var geo_fail_lat = 25.132402,
                geo_fail_lng = 121.739566,
                map = new GMaps({
                el: '#index_map',
                lat : geo_fail_lat,
                lng : geo_fail_lng,
                height: '558px',
                width: 'auto',
                zoom: 14
            });

            var init_marker = map.addMarker({
                lat: geo_fail_lat,
                lng: geo_fail_lng,
                title: '您的位置',
                icon: '/assets/green-dot.png',
                infoWindow: {
                    content: '<p>您的位置</p>'
                }
            });

            for (c = 0; c < coordinates.length; c++){
                lat_lng = coordinates[c].split(','),
                latitude = lat_lng[0],
                longitude = lat_lng[1],
                details = index_map.data('details')[coordinates[c]];
                content = [];
                for (t = 0; t < details.length; t++){
                    title = details[t]['title'],
                    story_id = details[t]['story_id'],
                    content_html = '<a href="stories/' + story_id + '">' + title + '</a>',
                    content.push(content_html);
                    map.addMarker({
                        lat: latitude,
                        lng: longitude,
                        icon: '/assets/red-dot.png',
                        infoWindow: {
                            content: content.join("<br/>")
                        }
                    });
                }
            }

            $('#toggle_map').on('shown.bs.modal', function () {
                map.refresh();
                if (typeof chosen_lat != 'undefined' && typeof chosen_lng != 'undefined') {
                    map.setCenter(chosen_lat, chosen_lng);
                }
                else {
                    map.setCenter(geo_fail_lat, geo_fail_lng);
                }
            });

            $('#users_city select').change(function(){
                $('#fail').hide();
                    GMaps.geocode({
                        address: $('#users_city select').val(),
                        callback: function(results, status) {
                            if (status == 'OK') {
                                 init_marker.setMap(null);
                                 if (typeof chosen_marker != 'undefined') {
                                    chosen_marker.setMap(null);
                                 }
                                 chosen_lat = results[0]['geometry']['location']['d']
                                 chosen_lng = results[0]['geometry']['location']['e']
                                 chosen_marker = map.addMarker({
                                    lat: parseFloat(chosen_lat) + 0.0001,
                                    lng: parseFloat(chosen_lng) + 0.0001,
                                    title: '您所選擇的定位點',
                                    icon: '/assets/green-dot.png',
                                 });
                                 map.setCenter(chosen_lat, chosen_lng);
                            }
                        }
                    });
                })
        },
        not_supported: function(){
            alert("Your browser does not support geolocation");
        }
    });
    $('#selected_city').select2();

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %a.close{"data-dismiss" => "alert"}
        %i.fa.fa-times-circle
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      - if user_signed_in?
        %a.navbar-brand{href: stories_path}
          Bigheart
          %i.fa.fa-heart
      -else
        %a.navbar-brand{href: stories_path}
          Bigheart
          %i.fa.fa-heart
    .navbar-collapse.collapse
      .nav.navbar-nav
        %li
          -#= link_to '閱讀所有故事', stories_path, {'data-no-turbolink' => true}
          = link_to '閱讀所有故事', stories_path
        %li
          = link_to '提供故事及資訊', new_story_path
        - if user_signed_in?
          -#%li
          -#  = link_to '我所發表的故事', stories_user_path(current_user.id)
          - if current_user.has_role? :admin
            %li
              = link_to '管理使用者', users_path
            %li
              = link_to '管理文章', manage_stories_path
            %li
              = link_to '登出', destroy_user_session_path, :method=>'delete'
        -else
          %li
            %a{"data-toggle" => "modal", :href => "#feedback"} 聯絡管理員
      -#.nav.navbar-nav.navbar-right
      -#  - if user_signed_in?
      -#    %li
      -#      - if current_user.uid.blank?
      -#        = link_to "#{current_user.name}", edit_user_registration_path
      -#      - else
      -#        = link_to "#{current_user.name}"
      -#    %li
      -#      = link_to '登出', destroy_user_session_path, :method=>'delete'
      -#  - else
      -#    = simple_form_for :user, url: new_user_session_path, :html => { :class => "navbar-form form-inline", :role => "form"} do |f|
      -#      .form-group
      -#        = f.input_field :email, :autofocus => true, class: "form-control", type: "email", placeholder: "email"
      -#      .form-group
      -#        = f.input_field :password, class: "form-control", type: "password", placeholder: "password"
      -#      = f.button :submit, '登入', class: "btn btn-primary btn-sm"
      -#      = link_to "Facebook登入", user_omniauth_authorize_path(:facebook), class: "btn btn-primary btn-sm"
    / /.navbar-collapse

app/views/layouts/application.html.haml
!!!
%html
  %head
    = display_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Bigheart"
      %meta{:content => content_for?(:description) ? yield(:description) : "Bigheart", :name => "description"}
        %link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css", :rel => "stylesheet"}/
        %link{href: "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", rel: "stylesheet"}/
        %link{href: "http://fonts.googleapis.com/css?family=Pacifico", rel: "stylesheet", type: "text/css"}/
        = stylesheet_link_tag "application", :media => "all"
        = stylesheet_link_tag "select2-bootstrap.css"
        = javascript_include_tag "http://maps.google.com/maps/api/js?libraries=geometry&sensor=true&language=zh-TW"
        = javascript_include_tag "application"
        %script{:src => "//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"}
        = javascript_include_tag "gmaps"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    #fb-root
    :javascript
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1&appId=250816725069932";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    = render 'layouts/navigation'
    = render 'layouts/feedback'
    #main{:role => "main"}
      .container
        .content
          = render 'layouts/messages'
          = yield
          %footer
      / ! end of .container
    / ! end of #main